name: Build and Deploy Backend

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rafli27/springboot-backend:latest

      # - name: Deploy to Server
      #   uses: appleboy/ssh-action@v0.1.6
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       cd /opt/repo-infra
      #       #login Dockerhub
      #       echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin
      #       # Pull image
      #       docker pull rafli27/springboot-backend:latest
      #       # Restart backend container
      #       docker ps -a
      #       docker-compose up -d --no-deps backend
      #       # cek log
      #       #docker-compose logs -f backend --tail=10
      #       #cleanup old images (keep 1)
      #       cd /opt/repo-infra
      #       ./cleanup-be.sh
